# Generated by Django 4.0.1 on 2022-01-16 18:24

from typing import Any, List

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=500, unique=True)),
                ("destination", models.CharField(max_length=500)),
                ("extra_info", models.CharField(blank=True, max_length=200)),
                ("status_code", models.SmallIntegerField(default=302)),
                ("referer_constraint", models.CharField(blank=True, max_length=200)),
                ("customized_error", models.CharField(blank=True, max_length=200)),
                ("is_logged", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, then the redirect will give a 404 instead.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accesses", models.BigIntegerField(default=0)),
                ("last_access", models.DateTimeField(auto_now=True)),
                (
                    "redir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="redirect.redirect",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Total Stats",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer", models.CharField(blank=True, max_length=250)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("accessed", models.DateTimeField(auto_now=True)),
                ("user_agent", models.CharField(blank=True, max_length=250)),
                (
                    "redir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="redirect.redirect",
                    ),
                ),
            ],
        ),
    ]
