# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0009_redirect_referer_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='customized_error',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
